FROM itdoginfo/openwrt-sdk-apk:09102025@sha256:06ead0c1fc37ca3e88a302beac66af18f4c0e903c5406642eacd1c5c791dcbf8

ARG PODKOP_VERSION
ENV PODKOP_VERSION=${PODKOP_VERSION}

COPY ./podkop /builder/package/feeds/utilities/podkop
COPY ./luci-app-podkop /builder/package/feeds/luci/luci-app-podkop

RUN make defconfig && \
    make package/podkop/compile -j1 V=s && \
    make package/luci-app-podkop/compile -j1 V=s